/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.banco.capa1_presentacion;

import com.banco.capa2_aplicacion.TransaccionServicio;
import com.banco.capa3_dominio.entidades.Tarjeta;
import com.banco.capa3_dominio.entidades.Transaccion;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Spider
 */

//sin plugins 
public class FormTransacciones extends javax.swing.JFrame {

    private Transaccion transaccion;
    private Tarjeta tarjeta;
    
    public FormTransacciones() {
    initComponents();
    this.getContentPane().setBackground(Color.WHITE);
    comboTransaccion.addItem("RETIRO");
    comboTransaccion.addItem("DEPÓSITO");
    }
    
    public void limpiar(){
        tarjeta = null; 
        transaccion= null;
        txtnumeroTarjeta.setText("");
        txtdestino.setText("");
        txtmonto.setText("");
        txtnumeroTarjeta.requestFocus();
        
    }
    
    public void activarRetiro(){
      if(!txtnumeroTarjeta.getText().isEmpty() && 
         !txtmonto.getText().isEmpty()){
        btnRetiro.setEnabled(true);
        }else{
        btnRetiro.setEnabled(false);
        }
    }
    public void activarDeposito(){
      if(!txtnumeroTarjeta.getText().isEmpty() && 
         !txtmonto.getText().isEmpty() && 
         !txtdestino.getText().isEmpty()){
        btnDeposito.setEnabled(true);
        }else{
        btnDeposito.setEnabled(false);
        }
    }
    
   
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retorna = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumeroTarjeta = new javax.swing.JTextField();
        txtmonto = new javax.swing.JTextField();
        btnRetiro = new javax.swing.JButton();
        comboTransaccion = new javax.swing.JComboBox<>();
        panelDestino = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtdestino = new javax.swing.JTextField();
        btnDeposito = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComprobante = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnComprobante = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRANSACCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nº TARJETA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 56, 79, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("MONTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 110, 56, 27));

        txtnumeroTarjeta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnumeroTarjeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnumeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnumeroTarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroTarjetaKeyTyped(evt);
            }
        });
        jPanel1.add(txtnumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 52, 142, 33));

        txtmonto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtmonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontoKeyTyped(evt);
            }
        });
        jPanel1.add(txtmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 106, 142, 34));

        btnRetiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRetiro.setText("REALIZAR RETIRO");
        btnRetiro.setEnabled(false);
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 34));

        comboTransaccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comboTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTransaccionActionPerformed(evt);
            }
        });
        jPanel1.add(comboTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 171, 39));

        panelDestino.setBackground(new java.awt.Color(255, 255, 255));
        panelDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DESTINO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nº TARJETA");

        txtdestino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtdestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtdestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdestinoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdestinoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelDestinoLayout = new javax.swing.GroupLayout(panelDestino);
        panelDestino.setLayout(panelDestinoLayout);
        panelDestinoLayout.setHorizontalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDestinoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelDestinoLayout.setVerticalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 171, -1));

        btnDeposito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeposito.setText("REALIZAR DEPÓSITO");
        btnDeposito.setEnabled(false);
        btnDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 250));
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMPROBANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtComprobante.setEditable(false);
        txtComprobante.setColumns(20);
        txtComprobante.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtComprobante.setRows(5);
        txtComprobante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtComprobante);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("GERENAR COMPROBANTE ");

        btnComprobante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnComprobante.setText("GENERAR COMPROBANTE");
        btnComprobante.setEnabled(false);
        btnComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobanteActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4288564bankingbusinesscashincomemoney-115792_115720.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addComponent(btnComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 254, 480, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void comboTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTransaccionActionPerformed
    String opciones = (String)comboTransaccion.getSelectedItem();
        if(opciones.equals("DEPÓSITO")){
          panelDestino.setVisible(true);
          btnDeposito.setVisible(true);
          btnRetiro.setVisible(false);
          limpiar();
          activarDeposito();
        }
        if(opciones.equals("RETIRO")){
          panelDestino.setVisible(false);
          btnDeposito.setVisible(false);
          btnRetiro.setVisible(true);
          limpiar();
          activarRetiro();
        
        }
    }//GEN-LAST:event_comboTransaccionActionPerformed

    private void txtnumeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroTarjetaKeyTyped
    String patron_de_entrada = "0123456789";
        if (txtnumeroTarjeta.getText().length() == 6 || 
        !patron_de_entrada.contains(String.valueOf(evt.getKeyChar())))
        evt.consume();
    }//GEN-LAST:event_txtnumeroTarjetaKeyTyped

    private void txtmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyTyped
    String patron_de_entrada = "0123456789";
        if (txtmonto.getText().length() == 4 || 
        !patron_de_entrada.contains(String.valueOf(evt.getKeyChar())))
        evt.consume();
    }//GEN-LAST:event_txtmontoKeyTyped

    private void txtdestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdestinoKeyTyped
    String patron_de_entrada = "0123456789";
        if(txtdestino.getText().length() == 6 || 
        !patron_de_entrada.contains(String.valueOf(evt.getKeyChar())))
        evt.consume();
    }//GEN-LAST:event_txtdestinoKeyTyped

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        int origen = Integer.parseInt(txtnumeroTarjeta.getText());
        int retirorealizado;

        TransaccionServicio transaccionServicio = new TransaccionServicio();
        try {
            tarjeta = transaccionServicio.buscarTarjeta(origen);
            if (tarjeta != null) {
                double monto = Double.parseDouble(txtmonto.getText());
                String tipotransaccion = comboTransaccion.getSelectedItem().toString();
                transaccion = new Transaccion(tarjeta, tipotransaccion, monto, origen);
                transaccion.FechaTransaccion(transaccion);
                int reponde = JOptionPane.showConfirmDialog(this, "¿Desea realizar el retiro?",
                        "Confirme el Proceso ",
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (reponde == JOptionPane.YES_OPTION) {
                    try {
                        retirorealizado = transaccionServicio.realizarRetiro(transaccion);
                        if (retirorealizado == 1) {
                            JOptionPane.showMessageDialog(null, "**Retiro con éxito, Genere su comprobante**");
                            btnRetiro.setEnabled(false);
                            btnComprobante.setEnabled(true);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error");
                    }
                } else if (reponde == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "** Transacción Cancelada **");
                    limpiar();
                }
            } else {
                JOptionPane.showMessageDialog(null, "** El Nª de la tarjeta no existe **");
                limpiar();
                activarRetiro();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
   
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        int origen = Integer.parseInt(txtnumeroTarjeta.getText());
        int destino = Integer.parseInt(txtdestino.getText());
        int depositorealizado;
        TransaccionServicio realizartransaccion = new TransaccionServicio();
        // validar tarjeta origen    
        try {
            tarjeta = realizartransaccion.buscarTarjeta(origen);
            if (tarjeta != null) {
                //JOptionPane.showMessageDialog(null,"** La tarjeta origen existe **");
            } else {
                JOptionPane.showMessageDialog(null, "** La tarjeta origen no existe **");
                limpiar();
                activarDeposito();
            }
            ///////////////////////////////////////////////////////////////////////////////////////    
            // validar iddestino
            ////////////////////////////////////////////////////////////////////////////////////////    
            // si las tarjetas existen se realizará el depósito    
            if (tarjeta != null) {
                double monto = Double.parseDouble(txtmonto.getText());
                String tipotransaccion = comboTransaccion.getSelectedItem().toString();
                transaccion = new Transaccion(tarjeta, tipotransaccion, monto, origen, destino);
                transaccion.FechaTransaccion(transaccion);
                int reponde = JOptionPane.showConfirmDialog(this, "¿Desea realizar el Deposito?",
                         "Confirme el Proceso",
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (reponde == JOptionPane.YES_OPTION) {
                    try {
                        depositorealizado = realizartransaccion.realizarDeposito(transaccion);
                        transaccion.getFechaTransaccion();
                        if (depositorealizado == 1) {
                            JOptionPane.showMessageDialog(null, "Depósito con éxito");
                            btnDeposito.setEnabled(false);
                            btnComprobante.setEnabled(true);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                } else if (reponde == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "** Transacción Cancelada **");
                    limpiar();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobanteActionPerformed
         String opciones = (String)comboTransaccion.getSelectedItem();
         if(opciones.equals("DEPÓSITO")){
         txtComprobante.append("--------------------------" + "\n"); 
         txtComprobante.append(" Fecha:" + transaccion.getFechaTransaccion()+ "\n");
         txtComprobante.append(" Nº Tarjeta: "  + txtnumeroTarjeta.getText()+ "\n");
         txtComprobante.append(" Tipo: " + comboTransaccion.getSelectedItem()+ "\n"); 
         txtComprobante.append(" Monto: " + txtmonto.getText()+ "\n");
         txtComprobante.append(" Tarjeta Destino: " + txtdestino.getText()+ "\n"); 
         txtComprobante.append("--------------------------" + "\n"); 
        }
        if(opciones.equals("RETIRO")){
         txtComprobante.append("--------------------------" + "\n");    
         txtComprobante.append(" Fecha:" + transaccion.getFechaTransaccion()+ "\n");
         txtComprobante.append(" Nº Tarjeta:" + txtnumeroTarjeta.getText()+ "\n");
         txtComprobante.append(" Tipo:" + comboTransaccion.getSelectedItem()+ "\n");
         txtComprobante.append(" Monto:" + txtmonto.getText()+ "\n");
         txtComprobante.append("--------------------------" + "\n"); 
        
        }
        limpiar();
         
    }//GEN-LAST:event_btnComprobanteActionPerformed

    private void txtnumeroTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroTarjetaKeyReleased
       activarRetiro();
    }//GEN-LAST:event_txtnumeroTarjetaKeyReleased

    private void txtmontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyReleased
       activarRetiro();
    }//GEN-LAST:event_txtmontoKeyReleased

    private void txtdestinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdestinoKeyReleased
       activarDeposito();
    }//GEN-LAST:event_txtdestinoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransacciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobante;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboTransaccion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDestino;
    public static javax.swing.ButtonGroup retorna;
    private javax.swing.JTextArea txtComprobante;
    private javax.swing.JTextField txtdestino;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtnumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
